const TimeVar = function() {
  this.SECONDS_IN_MINUTE = 60;
  this.MINUTES_IN_HOUR = 60;
  this.SECONDS_IN_HOUR = this.MINUTES_IN_HOUR * this.SECONDS_IN_MINUTE; // 3600
  this.MILLISECONDS_IN_SECOND = 1000;
  this.HOURS_IN_DAY = 24;
  this.MINUTES_IN_DAY = this.HOURS_IN_DAY * this.MINUTES_IN_HOUR; // 1440
  this.SECONDS_IN_DAY = this.HOURS_IN_DAY * this.SECONDS_IN_HOUR; // 86400
  this.MILLISECONDS_IN_DAY = this.SECONDS_IN_DAY * this.MILLISECONDS_IN_SECOND; // 86400000
};
