function TimeVar () {}
TimeVar.SECONDS_IN_MINUTE = 60;
TimeVar.MINUTES_IN_HOUR = 60;
TimeVar.SECONDS_IN_HOUR = TimeVar.MINUTES_IN_HOUR * TimeVar.SECONDS_IN_MINUTE; // 3600
TimeVar.MILLISECONDS_IN_SECOND = 1000;
TimeVar.HOURS_IN_DAY = 24;
TimeVar.MINUTES_IN_DAY = TimeVar.HOURS_IN_DAY * TimeVar.MINUTES_IN_HOUR; // 1440
TimeVar.SECONDS_IN_DAY = TimeVar.HOURS_IN_DAY * TimeVar.SECONDS_IN_HOUR; // 86400
TimeVar.MILLISECONDS_IN_DAY = TimeVar.SECONDS_IN_DAY * TimeVar.MILLISECONDS_IN_SECOND; // 86400000
